name: guppe_shappe
description: "Chatting App"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  #fire base initialise
  firebase_core: ^3.5.0

  #for handling firebase auth
  firebase_auth: ^5.3.0
  
  # for google sign in
  google_sign_in: ^6.2.1

  #clod flirebase data base
  cloud_firestore: ^5.4.2

  # image showing 
  cached_network_image: ^3.4.1

  #for choosing images
  image_picker: ^1.1.2

  #for firebase storage
  firebase_storage: ^12.3.3















  # laucher icon
  # flutter_launcher_icons: ^0.14.0

# flutter_launcher_icons:
#   android: "guppeshuppe_icon"
#   ios: true
#   image_path: "assets/logos/guppeshappelogo.png"
#   min_sdk_android: 21 
#   remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/logos/




  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
